SELECT DISTINCT 
    grn.id AS id,
    UPPER(grn.code) AS grn_code,
    UPPER(JSON_VALUE(jt, '$.inv.name')) AS inv_name,
    UPPER(JSON_VALUE(jt, '$.inv.sku')) AS inv_sku,
    UPPER(JSON_VALUE(jt, '$.inv.procurementUnit')) AS procurement_unit,
    UPPER(JSON_VALUE(jt, '$.inv.stockingUnit')) AS stocking_unit,
    JSON_VALUE(jt, '$.inv.procurementUnit') AS pu_to_su_ratio,
    UPPER(JSON_VALUE(jt, '$.inv.vat.name')) AS vat_name,
    JSON_VALUE(jt, '$.inv.vat.rate') AS vat_rate,
    UPPER(grn.vendor_code) AS vendor_code,
    UPPER(ven.name) AS vendor_name,
    UPPER(grn.lpo_code) AS lpo_code,
    UPPER(grn.invoice_no) AS invoice_no,
    UPPER(grn.status) AS grn_status,
    UPPER(grn.zone_code) AS zone_code,
    UPPER(sz.name) AS zone_name,
    FORMAT("%'d", CAST(JSON_VALUE(jt, '$.lpoAccounting.qty') AS int64)) AS lpo_qty,
    FORMAT("%'.2f", CAST(JSON_VALUE(jt, '$.lpoAccounting.unitCostWithoutVat') AS float64)) AS lpo_unit_cost_without_vat,
    FORMAT("%'.2f", CAST(JSON_VALUE(jt, '$.lpoAccounting.unitCostWithVat') AS float64)) AS lpo_unit_cost_with_vat,
    FORMAT("%'.2f", CAST(JSON_VALUE(jt, '$.lpoAccounting.totalCostWithVat') AS float64)) AS lpo_total_cost_with_vat,
    FORMAT("%'.2f", CAST(JSON_VALUE(jt, '$.lpoAccounting.totalVatAmount') AS float64)) AS lpo_total_vat_amount,
    FORMAT("%'d", CAST(JSON_VALUE(jt, '$.invoiceAccounting.qty') AS int64)) AS inv_qty,
    FORMAT("%'.2f", CAST(JSON_VALUE(jt, '$.invoiceAccounting.unitCostWithoutVat') AS float64)) AS inv_unit_cost_without_vat,
    FORMAT("%'.2f", CAST(JSON_VALUE(jt, '$.invoiceAccounting.unitCostWithVat') AS float64)) AS inv_unit_cost_with_vat,
    FORMAT("%'.2f", CAST(JSON_VALUE(jt, '$.invoiceAccounting.totalCostWithVat') AS float64)) AS inv_total_cost_with_vat,
    FORMAT("%'.2f", CAST(JSON_VALUE(jt, '$.invoiceAccounting.totalVatAmount') AS float64)) AS inv_total_vat_amount,
    FORMAT("%'d", CAST(JSON_VALUE(jt, '$.actualAccounting.qty') AS int64)) AS actual_qty,
    FORMAT("%'.2f", CAST(JSON_VALUE(jt, '$.actualAccounting.unitCostWithoutVat') AS float64)) AS actual_unit_cost_without_vat,
    FORMAT("%'.2f", CAST(JSON_VALUE(jt, '$.actualAccounting.unitCostWithVat') AS float64)) AS actual_unit_cost_with_vat,
    FORMAT("%'.2f", CAST(JSON_VALUE(jt, '$.actualAccounting.totalCostWithVat') AS float64)) AS actual_total_cost_with_vat,
    FORMAT("%'.2f", CAST(JSON_VALUE(jt, '$.actualAccounting.totalVatAmount') AS float64)) AS actual_total_vat_amount,
    FORMAT_DATE("%Y-%m-%d %H:%M:%S", grn.created_date) AS created_date,
    FORMAT_DATE("%Y-%m-%d %H:%M:%S", DATETIME(grn.created_date, 'Africa/Nairobi')) AS created_date_kenya,
    UPPER(grn.created_by) AS created_by,
    UPPER(grn.created_by_name) AS created_by_name,
    FORMAT_DATE("%Y-%m-%d %H:%M:%S", grn.last_modified_date) AS last_modified_date,
    FORMAT_DATE("%Y-%m-%d %H:%M:%S", DATETIME(grn.last_modified_date)) AS last_modified_date_kenya,
    UPPER(grn.last_modified_by) AS last_modified_by,
    UPPER(grn.last_modified_by_name) AS last_modified_by_name
FROM `kyosk-prod.inventory.tbl_goods_received_note` grn
LEFT JOIN UNNEST(JSON_QUERY_ARRAY(grn_items, '$')) AS jt
LEFT JOIN `kyosk-prod.inventory.tbl_vendor` ven ON grn.vendor_code = ven.code
LEFT JOIN `kyosk-prod.inventory.tbl_service_zone` sz ON grn.zone_code = sz.code;