select 'Athi River' as territory, -1.4275556 as warehouse_latitude, 36.9704444 as warehouse_longitude union all 
                        select 'Eastlands' , -1.3241389  , 36.867  union all
                        select 'Eldoret'  , 0.5201846  ,35.2563265  union all
                        select 'Embu'  , -0.54203   , 37.4542503  union all
                        select 'Juja'  , -1.1081111   ,37.0138611  union all
                        select 'Karatina'  , -0.4731389   ,  37.1262222  union all
                        select 'Kawangware'  , -1.28875   , 36.7517778  union all
                        select 'Kiambu'  ,  -1.2284444 ,  36.6881944 union all
                        select 'Kisii'  , -0.6713333  , 34.7678889  union all
                        select 'Kisumu1'  , -0.0879444  , 34.7596667  union all
                        select 'Majengo Mombasa'  , -4.0519167  ,39.6583611  union all
                        select 'Meru'  , -1.2770781  ,36.8146693  union all
                        select 'Mtwapa Mombasa'  , -3.9406389   ,39.7465278  union all
                        select 'Nakuru'  , -0.2829722   , 36.1188889  union all
                        select 'Ongata Rongai'  , -1.3989167  ,36.7250278  union all
                        select 'Ruai'  , -1.2285389  , 36.9890257  union all
                        select 'Ruiru'  , -1.2286944  ,36.9891111  union all
                        select 'Thika Rd'  , -1.2420833  ,36.8763611  union all
                        select 'Voi'  , -3.39025  ,38.57225